Allow converter.optional to take a converter such as converter.pipe as its argument
python-attrs/attrs pull request #1372
Opened 2024-11-13 14:54 UTC by filbranden

# Summary

Allow `converter.optional` to take a Converter such as `converter.pipe` as its argument.

Fixes #1348

# Pull Request Check List

- [x] Do **not** open pull requests from your `main` branch – **use a separate branch**!
  - There's a ton of footguns waiting if you don't heed this warning. You can still go back to your project, create a branch from your main branch, push it, and open the pull request from the new branch.
  - This is not a pre-requisite for your pull request to be accepted, but **you have been warned**.
- [x] Added **tests** for changed code.
  Our CI fails if coverage is not 100%.
- [ ] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/main/tests/strategies.py).
- [ ] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [ ] ...and used in the stub test file `tests/typing_example.py`.
    - [ ] If they've been added to `attr/__init__.pyi`, they've *also* been re-imported in `attrs/__init__.pyi`.
- [ ] Updated **documentation** for changed code.
    - [ ] New functions/classes have to be added to `docs/api.rst` by hand.
    - [ ] Changes to the signatures of `@attr.s()` and `@attrs.define()` have to be added by hand too.
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
          The next version is the second number in the current release + 1.
          The first number represents the current year.
          So if the current version on PyPI is 22.2.0, the next version is gonna be 22.3.0.
          If the next version is the first in the new year, it'll be 23.1.0.
      - [ ] If something changed that affects both `attrs.define()` and `attr.s()`, you have to add version directives to both.
- [ ] Documentation in `.rst` and `.md` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/main/changelog.d).
- [ ] Consider granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so maintainers can fix minor issues themselves without pestering you.

2024-11-14 15:24 UTC, Hnasar requested changes
Thanks for starting on a fix!

2024-11-14 15:32 UTC, filbranden commented on src/attr/converters.py
> +            return converter(val, inst, field)
Actually a `Converter` instance always takes three arguments: https://github.com/python-attrs/attrs/blob/13e9a6aaeac156bf792878eceaba10321728fa36/src/attr/_make.py#L2712-L2725

The callable it takes as an argument can take one, two or three, but the `Converter` class normalizes it to always take three arguments

So I believe this is correct

I think the typing information might need an update, to accept `Callable[[Any], Any] | Converter`  but I think that's a separate issue so maybe we should follow up on that on a separate PR?

2024-11-17 10:19 UTC, hynek approved these changes
Thanks for sorting it out yourself y'all! Feel free to open a PR re the typing issue you mentioned.

2024-11-17 10:19 UTC, hynek commented on tests/test_converters.py
> +        assert None is c1.x
```suggestion

        assert None is c1.x
```

2024-11-17 10:19 UTC, hynek commented on tests/test_converters.py
> +        assert True is c2.x
```suggestion

        assert True is c2.x
```

2024-11-17 11:18 UTC, merged

2024-11-18 06:02 UTC, filbranden commented
Thanks for merging @hynek !

I have a follow up on typing on #1373 but looks like that's still failing CI, looks like mypy on 3.10+ breaks with the error in the comments (even though `tox -e py310-mypy` itself doesn't fail), I'll take another look later see if I can figure out why it's breaking.

I also posted #1374 to fix another issue I uncovered in converters, in a situation where they evaluate to False. Long story short, but doing an explicit comparison to None fixes that and I believe it makes sense here.

Cheers!