Add Attribute.alias
python-attrs/attrs pull request #950
Opened 2022-04-09 20:23 UTC by asford

# Summary

Spike implementation for #945.

# Pull Request Check List

- [ ] Added **tests** for changed code.
  Our CI fails if coverage is not 100%.
- [ ] New features have been added to our [Hypothesis testing strategy](https://github.com/python-attrs/attrs/blob/main/tests/strategies.py).
- [ ] Changes or additions to public APIs are reflected in our type stubs (files ending in ``.pyi``).
    - [ ] ...and used in the stub test file `tests/typing_example.py`.
    - [ ] If they've been added to `attr/__init__.pyi`, they've *also* been re-imported in `attrs/__init__.pyi`.
- [ ] Updated **documentation** for changed code.
    - [ ] New functions/classes have to be added to `docs/api.rst` by hand.
    - [ ] Changes to the signature of `@attr.s()` have to be added by hand too.
    - [ ] Changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).
          Find the appropriate next version in our [``__init__.py``](https://github.com/python-attrs/attrs/blob/main/src/attr/__init__.py) file.
- [ ] Documentation in `.rst` files is written using [semantic newlines](https://rhodesmill.org/brandon/2012/one-sentence-per-line/).
- [ ] Changes (and possible deprecations) have news fragments in [`changelog.d`](https://github.com/python-attrs/attrs/blob/main/changelog.d).
- [ ] Consider granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so maintainers can fix minor issues themselves without pestering you.

2022-04-09 20:28 UTC, asford commented on docs/extending.rst
> +   Data(public=42, _privatge='spam')
```suggestion
   Data(public=42, _private='spam')
```

2022-05-02 17:36 UTC, hynek requested changes
This looks all very good and thorough, just a bunch of questions and nits.

it also needs a newsfragment. make it sounds excited. :)

sorry for taking so long…whenever Attribute changes the diffs make me wann hide under the bed.

2022-05-02 17:36 UTC, hynek commented on src/attr/_funcs.py
> +        init_name = a.alias
this is actually a nice effect

2022-05-02 17:36 UTC, hynek commented on src/attr/_make.py
> +        ), "requires known field alias, should have been set via _ClassBuilder"
did you leave this in on purpose?

2022-05-02 17:36 UTC, hynek commented on docs/init.rst
> +.. _private_attributes:
If I see it correctly, there's no narrative documentation for the new feature?


Would you mind adding it here and into examples.rst somewhere around the handling of private attributes?

2022-05-25 07:30 UTC, hynek commented
Anything you need from my end? 😇

2022-11-13 17:28 UTC, asford reviewed
My turn to apologize for the slow turnaround.

I've applied the review comments, and believe this is ready for a final pass.

2022-11-13 17:54 UTC, asford commented on docs/extending.rst
> +Noting, that ``field_transformer`` receives `attrs.Attribute` instances before private-attribute handling.
Tidied and reworded.

2022-11-16 15:03 UTC, hynek commented
w00t! Thanks for coming back! I'll try to be faster this time! :)

2022-11-16 15:30 UTC, asford commented
Really appreciate your work on attrs.
Thanks for being stoked on the contribution!

2022-11-30 14:34 UTC, hynek commented on src/attr/_make.py
> +    .. versionchanged:: 21.5.0 *alias*
you have not :D

2022-11-30 14:34 UTC, hynek approved these changes
Nailed it a tiny nit aside!

Thank you so much for coming back, I know how difficult it is to pick up something like this after a long time.

2022-11-30 14:39 UTC, merged

2022-11-30 14:41 UTC, Tinche commented
Cool. Cattrs will be no problem, I can just bump the dependency to the latest version of attrs and implement it.

Mypy will be a bigger issue I think.

2022-11-30 14:42 UTC, hynek commented
given alias is a dataclass transform feature, shouldn't it work OOB?

2022-11-30 14:43 UTC, Tinche commented
Unsure, Mypy has a custom attrs plugin so I don't know if the dataclass_transform code path is in charge of this.

2022-11-30 14:59 UTC, hynek commented
aw looks like you're right. pyright works: #1063

mypy doesn't:

Adding 

```
AliasExample(without_alias=42, _with_alias=23)
```

gives me: `tests/typing_example.py:134: error: Unexpected keyword argument "_with_alias" for "AliasExample"; did you mean "with_alias" or "without_alias"?`

@Tinche 🐶🥺?

2022-11-30 15:14 UTC, hynek commented
yeah, it's super overdue too.

i'll try to get #1003 in ASAP (it's just an alias, so it should be just busywork) and push it out RSN.